### ISSUE TITLE
Assign fixed version to an issue.

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#201]
When I update the Issue, with FixedVersion i get response:

```
Redmine.Net.Api.Exceptions.RedmineException
  HResult=0x80131500
  Message=UpdateObject has invalid or missing attribute parameters: Target version is not included in the list

  Source=redmine-net452-api-signed
  Ślad stosu:
   at Redmine.Net.Api.Extensions.WebExtensions.HandleWebException(WebException exception, String method, MimeFormat mimeFormat)
   at Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload(RedmineManager redmineManager, String address, String actionType, String data, String methodName, NameValueCollection parameters)
   at Redmine.Net.Api.RedmineManager.UpdateObject[T](String id, T obj, String projectId)
   at Redmine.Net.Api.RedmineManager.UpdateObject[T](String id, T obj)
   at ITSEB.Redmine.Classess.IssueData.AktualizujZagadnienie() in E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Redmine\Classess\IssueData.cs:line 67
   at Jira2Redmine.Forms.Form1.btnVersionsSet_ItemClick(Object sender, ItemClickEventArgs e) in E:\TFS\ITSEB\Jira to Redmine importer\Jira2Redmine\Forms\Form1.cs:line 877
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnUnPressItem(DXMouseEventArgs e, RibbonHitInfo hitInfo)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnMouseUp(DXMouseEventArgs e)
   at DevExpress.XtraBars.Ribbon.Handler.RibbonHandler.OnMouseUp(DXMouseEventArgs e)
   at DevExpress.XtraBars.Ribbon.RibbonControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraBars.Ribbon.RibbonControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Wewnętrzny wyjątek 1:
WebException: Serwer zdalny zwrócił błąd: (422) Unprocessable Entity.
```

Please help

**Library version: 2.0.14
.NET4.5.2
Redmine 3.4.4**

**Comment by zapadi** [comment]
Can you show me how the issue object that you are trying to update looks like?

**Comment by ebartlomiej89** [comment]
I have class with Issue variable
`Issue i = new Issue();`

In the first step i load an existing issue:
```
 var Parameters = new NameValueCollection()
                {
                    { RedmineKeys.INCLUDE, RedmineKeys.RELATIONS }
                };

i = Manager.Redmine.RedmineManager.GetObject<Issue>(ID, Parameters);
```
where **ID** is a string variable with number of issue. 
After load the issue I set the variable FixedVersion:
`zagadnienie.FixedVersion = new IdentifiableName() { Id = VersionID };`
where **VersionID** is a number of version. The version is in project.
After this i update the issue
Manager.Redmine.RedmineManager.UpdateObject<Issue>(i.Id.ToString(), i);
where **i.Id** is identifier of issue and **i** is the issue object.

**Comment by ebartlomiej89** [comment]
The variable look that:
{[Issue: [Identifiable: Id=8], Project=[IdentifiableName: Id=1, Name=Anteeo - Integracja], Tracker=[IdentifiableName: Id=1, Name=Błąd], Status=[IdentifiableName: Id=5, Name=Zamknięty], Priority=[IdentifiableName: Id=5, Name=Natychmiastowy], Author=[IdentifiableName: Id=7, Name=Jacek Maroń], Category=, Subject=Błąd podczas wysyłania WZ, Description=Nieoczekiwany błąd sql podczas zapisu do BD dyspozycji nr: WZ 602/EXK/06/2015. String or binary data would be truncated.
Błąd aktualizacji adresu! - (1)
The statement has been terminated., StartDate=, DueDate=22.06.2015 00:00:00, DoneRatio=0, PrivateNotes=False, EstimatedHours=, SpentHours=0, CustomFields=, CreatedOn=30.01.2018 16:05:08, UpdatedOn=31.01.2018 17:40:48, ClosedOn=30.01.2018 16:11:33, Notes=, AssignedTo=[IdentifiableName: Id=14, Name=Szczepan Jach], ParentIssue=, FixedVersion=[IdentifiableName: Id=1, Name=], IsPrivate=False, Journals=, Changesets=, Attachments=, Relations=, Children=, Uploads=, Watchers=]}

**Comment by ebartlomiej89** [comment]
issue - A hash of the issue attributes:
        project_id
        tracker_id
        status_id
        priority_id
        subject
        description
        category_id
        **fixed_version_id - ID of the Target Versions (previously called 'Fixed Version' and still referred to as such in the API)**
        assigned_to_id - ID of the user to assign the issue to (currently no mechanism to assign by name)
        parent_issue_id - ID of the parent issue
        custom_fields - See Custom fields
        watcher_user_ids - Array of user ids to add as watchers (since 2.3.0)
        is_private - Use true or false to indicate whether the issue is private or not
        estimated_hours - Number of hours estimated for issue

**Comment by zapadi** [comment]
I don't understand what are trying to tell me.

if you will look at the code (IssueConverter.cs) will see the following: 
result.WriteIdIfNotNull(entity.FixedVersion, RedmineKeys.FIXED_VERSION_ID);

**Comment by ebartlomiej89** [comment]
OK.

Can you tell me why i get the response:
**UpdateObject has invalid or missing attribute parameters: Target version is not included in the list**

**Comment by zapadi** [comment]
You are trying to update the issue with the FixedVersionId of another project.

**Comment by ebartlomiej89** [comment]
Can you explane me. When I assign this version in redmine, in database i see data like in the picture.
![2018-02-01 21_11_24-192 168 0 6 _ localhost _ test_redmineimporter _ issues _ phpmyadmin 4 7 4](https://user-images.githubusercontent.com/17325104/35699596-d0f63720-0790-11e8-9f05-65ee0ff4f8d0.png)
